feat(pathfinder): Implement prototype version
daangn/karrotframe pull request #123
Opened 2022-02-18 20:49 UTC by irrationnelle

- a manual documentation is located [here](https://github.com/daangn/karrotframe/tree/feat/pathfinder/packages/pathfinder)
- Some issue (`queryParams` should be declared if not need, redundant conditional check without queryParams,  indentation issue) would be fixed soon.
- I have a plan to add more CLI options if need and the manual document would be supplemented more to understand easily with Korean.
- I would like to name `trailblazer` but I choose `pathfinder` because `pathfinder` would be more intuitive.

2022-02-21 05:54 UTC, tonyfromundefined requested changes

2022-02-21 05:54 UTC, tonyfromundefined commented on packages/pathfinder/README.md
> +## generated SDK
(Slack에도 남김) 이 부분 없어도 될거같아요!

2022-02-21 05:54 UTC, tonyfromundefined commented on packages/pathfinder/index.ts
> +const createSdk = async (metaData: {
```suggestion
const createSdk = async (metadata: {
```

2022-02-21 05:54 UTC, tonyfromundefined commented on packages/pathfinder/index.ts
> +  `${text.charAt(0).toUpperCase()}${text.slice(1)}`
https://www.npmjs.com/package/pascal-case

2022-02-21 05:54 UTC, tonyfromundefined commented on packages/pathfinder/index.ts
> +  `${text.charAt(0).toUpperCase()}${text.slice(1)}`
요 역할인거같은데 ㅎㅎ 라이브러리를 써도 좋을거같아요.

2022-02-21 05:54 UTC, tonyfromundefined commented on packages/pathfinder/index.ts
> +    path.join(path.resolve(), `/${targetSchema}`),
```suggestion
    path.resolve(`./${targetSchema}`)
```

이게 맞지 않나요?

2022-02-21 06:26 UTC, irrationnelle commented on packages/pathfinder/README.md
> +## generated SDK
넵 해당 부분은 삭제하고 피드백대로 example 을 더 보강하는 방법으로 진행할게요!

2022-02-21 06:28 UTC, irrationnelle commented on packages/pathfinder/index.ts
> +  `${text.charAt(0).toUpperCase()}${text.slice(1)}`
나중에 기여하실 분들을 위해 토니가 추천한 라이브러리를 도입해서 코드 가독성을 높일게요

2022-02-21 06:28 UTC, irrationnelle commented on packages/pathfinder/index.ts
> +    path.join(path.resolve(), `/${targetSchema}`),
넵 확인해보니 토니가 제안주신 코드가 맞아요. 수정할게요

2022-03-08 10:10 UTC, irrationnelle commented
@tonyfromundefined 리뷰 부탁드릴게요~

2022-03-08 10:16 UTC, tonyfromundefined approved these changes
JSON Schema는 .json으로 관리하는게 좋을거같아요~

2022-03-08 10:36 UTC, irrationnelle commented
@tonyfromundefined 5ad396e5ab5cb5167855f9cc5631473158f7e9c6 에서 반영했어요

merge 할게요!

2022-03-08 10:37 UTC, merged