fix(navigator): Add hideLeftButton option to hide back or close button from navbar
daangn/karrotframe pull request #137
Opened 2022-03-10 21:12 UTC by irrationnelle

2022-03-11 10:35 UTC, irrationnelle commented
Test codes will be added before merge

2022-03-15 09:19 UTC, tonyfromundefined requested changes

2022-03-15 09:19 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
```suggestion
          noBackButton={shouldHideLeftButton}
```

noBackButton 어때요?

- 위에 `noBorder`랑 맞춰주기
- `appendLeft`는 그대로 작동할텐데... `Left`를 가린다는게 모호함

2022-03-15 09:45 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
> noBackButton 어때요?

`noBackButton` 을 true 로 했을 때 close button 도 나타나지 않는 점이 마음에 걸려요.

> appendLeft는 그대로 작동할텐데... Left를 가린다는게 모호함

이런 측면에서 `hideLeftButton` 도 별로네요

2022-03-15 09:47 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
@tonyfromundefined 

슬랙 논의에서도 토니는 `hideBackButton` 을 제안했는데, `back` 으로 충분히 설명 가능하고 `close` 까지 커버해도 괜찮다고 생각하는 것 같아요.

혹시 이 부분에 대해 좀 더 토니의 생각을 들어볼 수 있을까요?

2022-03-15 10:01 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
아 이게 CLOSE까지 커버하는군요;; 저는 "백버튼"만 생각했어요. close 버튼은 Navigator에서 onClose 핸들러를 안 주면 숨겨지니까요.

2022-03-15 10:01 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
그럼 좀 verbose해도

`noBackAndCloseButton`은 어때요?

2022-03-15 10:09 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
> close 버튼은 Navigator에서 onClose 핸들러를 안 주면 숨겨지니까요.

아 맞아요 테스트 코드 작성할 때 이거 때문에 많이 당황했어요. 

제 경험에선 암묵적인 인터페이스라 생각했는데,

사용자 입장에서는 문서에서만 확실하게 명시해주면 `당연한` 인터페이스인지 궁금해지네요.

x 버튼에 default event 가 당연히 있을 것이라고 생각하는게 자연스러운지

x 버튼은 항상 명시적으로 event 를 선언하는 게 자연스러운지 고민이 드네요

2022-03-15 10:40 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
onClose를 안주면 숨겨진다기보다는 호출될 핸들러가 없는데 왜 X 버튼을 노출해야될까? -> 숨기자!

가 되어버린듯요... 근데 암묵적이라는건 동의해서, 차라리 onClose 핸들러를 required 필드로 만들어버리고, noClose가 ScreenHelmet에 있는게 더 나은거같아요.

2022-03-15 10:41 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
이거 back button 만 옵션 사용하도록 변경할게요. 다음과 같이 생각하고 낸 결론이에요.

- close 버튼을 눌렀을 때 default event 가 발생한다면 onClose 와 close button 을 보여주는 flag 변수는 분리하는 것이 맞다.
- 현재 close 버튼을 클릭했을 때 default event 는 발생하지 않는다. 가장 먼저 떠올릴 수 있는 default operation 은 창 닫기이지만 karrotframe 이 window.close 를 호출하는 것은 이상하다.
- 따라서 default event 를 적절하게 지원하지 않는 현재, 특별히 다루려는 이벤트가 없다면 close 버튼 역시 필요가 없고, 따라서 onClose 으로 버튼이 보여지는 것까지 관리하는 것이 타당하다.

2022-03-15 10:41 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
앗 동시에 답변을 달았군요

2022-03-15 10:46 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
토니의 솔루션은 default event 를 지원하지 않아도 event handler 와 flag 는 분리하는 것이 명시적인 코드이므로 의미가 있다는 접근이네요.

required 필드일 때 저는 종종 `const noop = () => {}` 같은 거 만들어서 넣어줬는데, 이 정도 불편함은 괜찮을 거 같아요. 따라서 찬성해요~

2022-03-15 10:48 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
근데 default event가 뭐에요?? 이해못함 ㅋㅋㅋ onClose를 말하시는거에요?

2022-03-15 10:51 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          hideLeftButton={shouldHideLeftButton}
> 근데 default event가 뭐에요?? 이해못함 ㅋㅋㅋ onClose를 말하시는거에요?

네 맞아요~

> "호출될 핸들러가 없는데 왜 X 버튼을 노출해야될까?" -> "숨기자!" 가 되어버린듯해요 ㅋㅋ

저도 이 생각에 동의했는데,

그러려면 x 버튼에 기본적으로 작동하는 핸들러가 없다는 것을 의미하니까요.

`기본적으로 작동하는 핸들러` -> default event 로 표현했어요. default handler 가 의미하는 바가 더 정확하네요.

2022-03-16 02:33 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
굳이 boolean 타입 필드에 `is`를 붙여야할까요? ㅎㅎ 이야기해보고 싶어요 ㅋㅋ

2022-03-16 04:57 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
네 저는 필요하다고 생각해요.

prefix / suffix 로 로 변수의 성격을 알 수 있으면 가독성이 올라가서 저는 무리해서 붙일 정도에요. 

무리해서 붙인다는 건, is 가 어색하면 should 를 쓰거나 has 를 쓸 정도라는 이야기에요.

널리 알려진 prefix / suffix 로 다음과 같은 것들이 떠오르는데요,

- boolean 에는 is prefix
- 배열을 사용할 때는 `s` 를 붙여서 복수형태로 표기 (이 부분은 사실 배열을 다루지 않다가 최종적으로 배열을 다루는 코드가 될 때는 종종 놓쳐요)

이외에도 저는 특정 라이브러리나 프레임워크의 prefix / suffix 도 컨벤션이 막지 않으면 항상 사용해요. rxjs 에서 observable 에 `$` 를 붙이는 등.

이런 부분들을 조합하면 코드 이해하기 훨씬 수월했어요.

같은 맥락에서 변수나 함수 이름도 굉장히 verbose 하게 짓는 편이에요.

2022-03-16 05:00 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
IDE 가 요즘은 굉장히 잘 보조해줘서 변수의 성격을 파악하는 건 사실 어렵지 않아요.

verbose 한 이름이나 prefix 로 굉장히 긴 함수나 클래스를 이해하는 데에 도움이 되긴 하지만, (도움이 크다기 보단 이거라도 있으니 다행이라는 느낌으로)

이 부분은 함수를 잘게 쪼개고, 클래스의 역할을 더 세분화하는 것으로 해결할 수 있는 문제이기도 해요.

2022-03-16 05:39 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
```suggestion
  const [isNoBackButton, setIsNoBackButton] = useState(false)
```

그럼 저는 요고 ㅎㅎ

2022-03-16 05:40 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
저는 함수인자에는 is 붙이는거 안하려고 하긴해요 ㅎㅎ

```
as-is:
isVisible: false

to-be:
visible: false
```

아래가 더 명확하다고 생각해서요 ㅎㅎ

2022-03-16 05:48 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
함수 매개변수로 boolean 타입을 받는 것이 함수 디자인에 좋지 않다 라는 글을 본 거 같은데요.

이거와는 다르게 명명법에 대해서만 이야기하시는 거죠?

2022-03-16 05:50 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
네네 ㅋㅋ 뭔가 저도 옛날엔 `is` 많이 붙였었는데... 그렇게 몇년간 하다보니, 좀 부질없음을 느껴요. 구조가 중요하지 미시적인 코드 한줄한줄 바꾼다고 가독성이 올라가나 싶어요. 그래서 이제는 키보드 덜 치자... 가 된듯해요 ㅋㅋ remix에서 `const` 안 쓰고 `let` 쓰는 느낌이랄까요.

> 함수 매개변수로 boolean 타입을 받는 것이 함수 디자인에 좋지 않다
오 이거 궁금한데 나중에 소개해주세요 ㅎㅎ

2022-03-16 05:59 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
> 전체적인 구조가 가독성에서 더 중요하지 미시적인 코드 한줄한줄 바꾼다고 가독성이 좋아지나 싶어서요.

맞아요. 이름이 도메인이나 오퍼레이션을 잘 설명한다는 전제를 두었을 때(변수명이나 함수명을 a,b,c 로 짓지 않는다는 전제)

prefix 나 suffix 을 챙기는 것보다 전체 구조를 더 챙기는 것이 가독성에 더 보탬이 되어요.

키보드 치는데 시간을 덜 쓰고 구조를 고민하는데 시간을 더 쓰는 것을 고려해봐야겠네요 ㅋㅋ 그런데 remix 에서 const 대신 let 쓰는 건 의외네요.

2022-03-16 06:03 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
> 함수 매개변수로 boolean 타입을 받는 것이 함수 디자인에 좋지 않다

로버트 마틴의 클린 코드인가 클린 아키텍쳐인가 책에서 본 거 같은데 flag 로 사용하는 값을 인자로 받는다는 것은 함수를 분리할 수 있는 기회를 버리고 생각없이 함수를 만드는 행위이다.. 같은 맥락으로 기억해요.

근데 같은 책에서 switch 문을 격리해서 정말 law 레벨의 함수에서만 switch 문을 내부에 가지고 있어야 한다 같은 이야길 해서 둘이 서로 상반된 이야기 아닌가? 라는 의문이 있어서 조금 와닿지 않았던 기억이..

해당 내용에 대해 발견하게 되면 다시 공유할게용

2022-03-16 06:12 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
[d5ed0b1](https://github.com/daangn/karrotframe/pull/137/commits/d5ed0b1a49badbe2002b230284b6f3f6a9077686)

react setter 함수 명명법의 일관성을 위해 `setIsNoBackButton` 으로 수정했어요

2022-03-16 06:47 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
https://github.com/remix-run/remix/blob/main/packages/remix-react/scroll-restoration.tsx
https://twitter.com/ryanflorence/status/1461476994646884355

2022-03-16 06:49 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
> 3 characters is less than 5. That's it.

멋지다

2022-03-16 06:50 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
const 대신 let 을 사용하지만 여전히 변수는 const 처럼 다루고 있네요 호오

2022-03-16 06:58 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
```typescript
const a = { b: 3 }
a.b = 4
```

가 가능하기 때문에 애초에 `const` 키워드가 거짓말하고 있다고 평가해요 ㅋㅋ

`const` 옹호자 논리라면

```typescript
const a = Object.freeze({ b: 3 })
a.b = 4 // Error!
```

이렇게 짜야하는데, 실제로 그들이 그렇게 짜고있나? => X

2022-03-16 07:00 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
그래서 남한테 들은 얘기, 어디서 본 이야기를 넘어서서, 진짜 뭐가 중요한건지 충돌하고 깊이 생각해야한다고 느껴요.

2022-03-16 07:05 UTC, tonyfromundefined approved these changes

2022-03-16 07:23 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +  const [isNoBackButton, setNoBackButton] = useState(false)
> 이렇게 짜야하는데, 실제로 그들이 그렇게 짜고있나? => 귀찮아서 안함 => ???

맞네요. 오브젝트나 배열에 한해서는 const 만으로는 제 역할을 못 하죠.

> 진짜 뭐가 중요한건지 충돌하고 깊이 생각해야한다고 느꼈어요

동의해요. 나름대로 한다고 생각했는데 아직도 당연하다 생각하는 부분들이 굉장히 많네요 ㅎㅎ..

2022-03-16 09:58 UTC, merged