fix(navigator): Add visible option for ScreenHelmet and preventSwipeBack option
daangn/karrotframe pull request #139
Opened 2022-03-11 02:35 UTC by irrationnelle

2022-03-11 10:24 UTC, irrationnelle commented
Test codes will be added soon

2022-03-15 09:18 UTC, tonyfromundefined requested changes

2022-03-15 09:18 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          preventBackSwipe={shouldPreventBackSwipe}
음 그때 어셔가 피드백 주셨던거 생각해봤는데요 ㅎ 그래서

```suggestion
          preventSwipeBack={shouldPreventBackSwipe}
```

요 이름이 더 낫지 않나 하는 생각이 들었어요

2022-03-15 09:18 UTC, tonyfromundefined commented on packages/navigator/src/components/Navbar.tsx
> +      data-testid="nav-bar"
```suggestion
      data-testid="navbar"
```

case는 파일명이랑 맞춰주는게 나을거같아요.

2022-03-15 09:18 UTC, tonyfromundefined commented on packages/navigator/src/components/Navbar.tsx
> +      data-testid="nav-bar"
data-testid는 빌드될때 사라지는지 궁금해요. Babel plugin 같은게 있나요?

2022-03-15 09:38 UTC, irrationnelle commented on packages/navigator/src/components/Navbar.tsx
> +      data-testid="nav-bar"
@tonyfromundefined 

> data-testid는 빌드될때 사라지는지 궁금해요. Babel plugin 같은게 있나요?

빌드 때 삭제할 수 있어요. [babel plugin](https://github.com/coderas/babel-plugin-jsx-remove-data-test-id) 도 있고요

당장은 필요없는 값이라 빌드 이후에 지울 수 있는데, 나중에 e2e 테스트 작성할 때도 사용할 수 있어서 "저는" 보통 prod 에 나갈 때도 남겨두는 편이에요.

data-testid 는 사용자 입장에서는 완전히 쓸모없는 값이라 data-testid 대신 aria-label 로 대체하는 방법도 있어요. 반대로 저는 aria-label 은 사용자에게 영향을 미치는 attribute 라서 사용을 꺼려요.

2022-03-15 09:41 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          preventBackSwipe={shouldPreventBackSwipe}
오.. 저는 그 때 4명 중 2인 이상이 preventBackSwipe 가 더 이해하기 쉽다고 해서 dx 가 이쪽이 더 나은가 보다 하고 바꿨는데, 토니는 어떤 면에서 더 낫다고 결론을 내린 거에요?

2022-03-15 10:03 UTC, tonyfromundefined commented on packages/navigator/src/components/Navbar.tsx
> +      data-testid="nav-bar"
아하 E2E때도 쓰이는군요 ㅋㅋ 좋아요~

2022-03-15 10:03 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          preventBackSwipe={shouldPreventBackSwipe}
더 표준어 같아서요 ㅋㅋ

2022-03-15 10:12 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          preventBackSwipe={shouldPreventBackSwipe}
이번에 확실히 잘 정해야겠네요. 

swipe 라는 개념을 명시적으로 코드내에 표시한 것이 이 PR 이 처음이라서 이번에 결정한 거가 다음 작업 때도 계속 영향을 미칠테니.

2022-03-15 10:28 UTC, irrationnelle commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          preventBackSwipe={shouldPreventBackSwipe}
[06d6aed](https://github.com/daangn/karrotframe/pull/139/commits/06d6aedfcfd4c06ac44b5e3026b5869806b56e7e)

여기에서 `preventSwipeBack` 으로 변경했어요. 애플 공식 개발자 페이지에는 딱히 언급은 없는데 포럼 등에서 back swipe 보다는 swipe back 으로 더 자주 사용해서요.

2022-03-15 10:43 UTC, tonyfromundefined commented on examples/spec/src/components/_pages/PageScreenHelmet.tsx
> +          preventBackSwipe={shouldPreventBackSwipe}
굿굿굿!

2022-03-15 10:48 UTC, irrationnelle commented
아 이거 request change 받아도 merge 가능하구나;

2022-03-15 10:55 UTC, merged