feat(navigator): navbar transition
daangn/karrotframe pull request #162
Opened 2022-04-26 13:47 UTC by irrationnelle

https://user-images.githubusercontent.com/10165823/165315197-2408ff50-f665-4688-9351-4080056b8b82.MP4

- visible false 일 때 기존에는 컴포넌트를 언마운트했는데, 이제는 translateY 로 viewport 바깥으로 밀어내요. 무거운 컴포넌트가 아니기 때문에 언마운트가 아니어도 성능에 큰 차이가 없을거라고 생각해요.

- nextTick helper 함수 내부에서 setTimeout 을 사용해요. 기존에는 Promise.resolve 를 사용했어요.

- vanilla-extract 의 assignInlineVars 를 사용해서 vars.navbar.animationDuration 과 vars.navbar.translateY 를 다루어요.

  - variant 를 추가하는 것이 더 복잡도를 늘린다고 판단하여 assignInlineVars 을 사용하기로 결정했어요

  - 추후 animationDuration 을 option 으로 받아 동적으로 다룰 경우 수정이 용이해요

  - 전체 코드에서 assignInlineVars 사용빈도가 아주 적기 때문에 사용을 지양하는 convention 이 따로 있거나, 스타일링 규칙을 따르지 않은 것이 아닐까 우려가 있어요.
  
  - navbar 를 viewport 위로 밀어낼 때에는, 바로 뒤의 screen 이 나타나지 않도록 variant 를 이용해서 background 를 하얀색으로 칠해요. 

- vars.navbar.animationDuration 는 mounted 가 true 일 때 0 이외의 값을 가져요

- vars.navbar.translateY 는 isNavbarVisible 이 true 일 때 0 이고 false 일 때 -2.75rem 이에요.

- 사파리에서 컴포넌트가 mount 될 때 transition 이 발생하지 않도록 screenHelmetVisible 의 초기값을 true 로 변경했어요 [참고](https://github.com/daangn/karrotframe/pull/161#issuecomment-1109504854)

- 테스트 코드를 수정했어요. 스냅샷을 사용해서 테스트해요. 
  - 기존 테스트 코드는 테스트 대상이었던 navbar 컴포넌트가 mount / unmount 되는지 확인이 가능했어요.
  - 현재는 viewport 밖으로 밀어내면서 navbar 컴포넌트가 여전히 존재하기 때문에 navbar 컴포넌트의 존재 여부를 확인하는 방법으로 테스트가 불가능하고, translate 값을 대조하는 방식으로 테스트가 가능해요. 해당 방법은 구현을 테스트하는 것이라 테스트 유지보수성을 높여요. 하지만 테스트 작성은 더 verbose 하고 까다로워져요. 그래서 스냅샷 테스트로 대체하였어요. 스냅샷 테스트 역시 작은 변화에도 쉽게 깨지기 때문에 테스트의 유지보수성을 높이지만 테스트 작성자체는 쉽고 빠르기 때문이에요.

2022-04-27 01:38 UTC, ginger-kang approved these changes
👍

2022-04-28 02:20 UTC, tonyfromundefined requested changes
감사합니당!

2022-04-28 02:20 UTC, tonyfromundefined commented on packages/navigator/src/components/Card.css.ts
> +    isTopAndIsNoNavbarVisible: {
```suggestion
    isTopAndIsNavbarNotVisible: {
```

2022-04-28 02:20 UTC, tonyfromundefined commented on packages/navigator/src/hooks/useMounted.ts
> +    nextTick(() => mount())
```suggestion
export function useMounted() {
  const [mounted, mount] = useReducer(() => true, false)

  useEffect(() => {
    nextTick(() => mount())
```

한칸 띄어주시면 더 좋을거같아요~ ㅎㅎ

2022-04-28 02:25 UTC, irrationnelle commented on packages/navigator/src/components/Card.css.ts
> +    isTopAndIsNoNavbarVisible: {
- 명명규칙을 일관성있게 가져가려고 No 를 택했는데 방금 다시 확인해보니 모두 Not 으로 되어있네요. 체크 감사합니당

2022-04-28 02:28 UTC, tonyfromundefined requested changes

2022-04-28 02:28 UTC, tonyfromundefined commented on packages/navigator/src/hooks/useMounted.ts
> +export function useMounted() {
```suggestion
export function useMountedAfterTick() {
```

이런 이름이 더 좋을거같아요 ㅎㅎ 함수 이름만 봐서는 useEffect에서 mount()를 바로 부를거같아서요.

2022-04-28 02:30 UTC, irrationnelle commented on packages/navigator/src/hooks/useMounted.ts
> +export function useMounted() {
@tonyfromundefined 

useMounted 가 인자로 boolean 타입 afterTick 을 받는 것은 어떤가요?

2022-04-28 02:36 UTC, tonyfromundefined commented on packages/navigator/src/hooks/useMounted.ts
> +export function useMounted() {
올 굿

2022-04-28 02:56 UTC, tonyfromundefined approved these changes

2022-04-28 02:59 UTC, merged