Remove querystring dependency
daangn/karrotframe pull request #68
Opened 2021-07-07 08:50 UTC by cometkim

2021-07-08 06:30 UTC, tonyfromundefined requested changes

2021-07-08 06:30 UTC, tonyfromundefined commented on packages/karrotframe/src/navigator/Navigator.tsx
> +        _present: searchParams.get('_present'),
```typescript
const _si = searchParams.get('_si')
const _present = searchParams.get('_present')
```

2021-07-08 06:30 UTC, tonyfromundefined commented on packages/karrotframe/src/navigator/useNavigator.ts
> +    [history, screenInfo]
오 굿!

2021-07-08 06:30 UTC, tonyfromundefined commented on packages/karrotframe/src/navigator/Navigator.tsx
> +        _present: searchParams.get('_present'),
팀 저번에 suggest changes? 쓰셔서 해보고싶은데 ㅋㅋ 어떻게 하는건지 모르겠네요 ㅋㅋ

2021-07-08 06:31 UTC, tonyfromundefined commented
prerelease/0.16에 main쪽 리베이스 받아서 푸시해놓았어요~ 리베이스 부탁드려요~

2021-07-08 06:45 UTC, cometkim commented on packages/karrotframe/src/navigator/Navigator.tsx
> +        _present: searchParams.get('_present'),
![image](https://user-images.githubusercontent.com/9696352/124875103-778a2d00-e003-11eb-9fca-23d7cc46f992.png)
요 버튼

2021-07-08 06:46 UTC, cometkim commented on packages/karrotframe/src/navigator/Navigator.tsx
> +      const present = searchParams.get('_present')
왜 명시적으로 키 이름을 노출하나요? 오히려 한 번 더 리팩토링해서 세부내용은 캡슐화 하려고 생각했는데요.

2021-07-08 10:04 UTC, tonyfromundefined commented on packages/karrotframe/src/navigator/Navigator.tsx
> +      const present = searchParams.get('_present')
하나로 통일하려는 목적이 좀 더 있는거같구요. searchParam에서 온 값이라는게 변수명에서 직접적으로 드러났으면 좋겠어요. 지금은 `_`로 표시가 되는거같아서 별 생각은 안했는데 이것도 넘 암묵적이긴 하네요 ㅎㅎ

```typescript
const searchParamScreenInstanceId = searchParams.get('_id')
```

이건 뭔가 좀 긴거같고... 그냥 변수로 따로 안담고 searchParams.get('_id') 구문을 그때그때 써도 될거같구요.

2021-07-08 10:45 UTC, cometkim commented on packages/karrotframe/src/navigator/Navigator.tsx
> +      const present = searchParams.get('_present')
> 하나로 통일하려는 목적이 좀 더 있는거같구요. searchParam에서 온 값이라는게 변수명에서 직접적으로 드러났으면 좋겠어요.

`const { screenInstanceId, present } = getNavigatorParams(searchParams)`

2021-07-12 02:38 UTC, tonyfromundefined commented on packages/karrotframe/src/navigator/Navigator.tsx
> +      const present = searchParams.get('_present')
좋아요~

2021-07-12 03:31 UTC, tonyfromundefined commented
확인했어요~ 테스트해보고 머지할께요~

2021-07-12 03:53 UTC, tonyfromundefined commented
<img width="542" alt="스크린샷 2021-07-12 오후 12 52 35" src="https://user-images.githubusercontent.com/20325202/125228631-19fe2500-e310-11eb-84fc-80f09e114488.png">

요런 에러가 있네요 ㅠ

2021-07-12 04:00 UTC, cometkim commented on packages/karrotframe/src/navigator/useNavigator.ts
> +        const { pathname, searchParams } = new URL(to, /* dummy */ 'a://')
```suggestion
        const { pathname, searchParams } = new URL(to, /* dummy */ 'file://')
```

2021-07-12 04:04 UTC, tonyfromundefined approved these changes
LGTM!

2021-07-12 04:04 UTC, merged